import { useEffect, useState } from 'react'
import './App.css'
import './about.css'

const pages = [
  { id: 'price', title: '料金表', en: 'PRICE LIST', icon: '▦' }, { id: 'order', title: 'オーダーの流れ', en: 'ORDER GUIDE', icon: '☝' }, { id: 'print', title: 'プリントの種類', en: 'PRINT TYPES', icon: '♧' }, { id: 'data', title: '入稿データの作り方', en: 'DATA GUIDE', icon: '⌁' }, { id: 'faq', title: 'よくある質問', en: 'Q&A', icon: 'Q' }, { id: 'about', title: 'asoBeについて', en: 'ABOUT US', icon: 'a' },
]
const PageHeading = ({ label, en, intro }) => <><p className="eyebrow">{en}</p><h1>{label}</h1><p className="intro">{intro}</p></>

function Price() { return <><PageHeading label="料金表" en="PRICE LIST" intro="内容・枚数・サイズで変わるため、まずは目安をご確認ください。LINEで画像を送るだけでもお見積もりできます。"/><div className="note">表示はすべて税込。ウェア代 + 製版・フィルム代 + プリント代の合計です。</div><section className="price-grid"><article><h2>シルクスクリーン</h2><p className="minor">大ロット・単色〜多色向け</p><dl><dt>ウェア代（Tシャツ例）</dt><dd>1枚 ¥1,100〜</dd><dt>製版代（1色・1デザイン）</dt><dd>¥4,400〜</dd><dt>プリント代</dt><dd>1回 ¥550〜</dd></dl><p className="minor">製版サイズ：小〜大 ¥4,400 / 特大 ¥8,800</p></article><article><h2>DTFプリント</h2><p className="minor">フルカラー・1枚から向け</p><dl><dt>ウェア代（Tシャツ例）</dt><dd>1枚 ¥1,100〜</dd><dt>フィルム代（10×30cm）</dt><dd>¥1,000</dd><dt>フィルム代（40×50cm）</dt><dd>¥1,800</dd><dt>プリント代</dt><dd>1回 ¥550〜</dd></dl></article></section><p className="caution">デザイン・アイテム・枚数によって料金は変動します。詳しいお見積もりはLINEでご相談ください。</p></> }
function Order() { const steps=[['1','お問い合わせ・ヒアリング','作りたいウェア、デザインのイメージ、枚数をLINEでお知らせください。具体的に決まっていなくても大丈夫です。'],['2','デザイン確定・お見積もり','データをご提出、または一緒に内容を固めて最終金額をご案内します。'],['3','プリント制作','用途に合う方法をご提案し、1枚ずつ丁寧にプリントします。'],['4','検品・納品','検品後にお渡し・発送します。通常はデザイン確定後、約2〜3週間です。']]; return <><PageHeading label="オーダーの流れ" en="ORDER GUIDE" intro="はじめてでも、LINEで「作りたいもの」を送るだけでスタートできます。"/><ol className="steps">{steps.map(([n,t,d])=><li key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></li>)}</ol><p className="caution">お急ぎの場合や、14〜18営業日程度をご希望の場合は事前にご相談ください。</p></> }
function Print() { return <><PageHeading label="プリントの種類" en="PRINT TYPES" intro="デザインと枚数に合わせて、最適な方法をご提案します。"/><section className="compare"><article><div className="method-mark">S</div><h2>シルクスクリーン</h2><p className="lead">圧倒的な耐久性と発色。</p><ul><li>同じデザインをたくさん作るほどお得</li><li>単色から多色まで対応</li><li>Tシャツ、パーカー、ナイロン、スポーツウェアなどに</li></ul><p className="tag">チームウェア・ユニフォームに</p></article><article><div className="method-mark">D</div><h2>DTFプリント</h2><p className="lead">フルカラーを、1枚から自由に。</p><ul><li>グラデーション・写真もきれいに表現</li><li>版が不要で小ロットに最適</li><li>細かな線や文字もくっきり定着</li></ul><p className="tag">イベント・ギフト・多彩なデザインに</p></article></section></> }
function Data() { return <><PageHeading label="入稿データの作り方" en="DATA GUIDE" intro="Illustrator（AI）形式での入稿がおすすめです。難しい場合も、まずはお気軽にお送りください。"/><section className="data-list"><article><b>01</b><div><h2>データを送る</h2><p>AI形式が最適です。写真や手書きラフ、参考画像でもご相談いただけます。</p></div></article><article><b>02</b><div><h2>仕上がりを伝える</h2><p>プリントしたい位置・おおよその大きさ・ウェアの色を一緒にお知らせください。</p></div></article><article><b>03</b><div><h2>確認して進める</h2><p>データの調整やプリント可能な形への調整もサポートします。確認後に制作開始です。</p></div></article></section><div className="note">スマホから「この画像でTシャツを作りたい」と送っていただくだけでもOKです。</div></> }
function Faq() { const qs=[['何枚から注文できますか？','1枚からご注文いただけます。DTFは小ロットに向き、シルクスクリーンは同じデザインをまとめて作る場合におすすめです。'],['デザインデータはどう渡せばいいですか？','Illustrator（AI）形式がおすすめです。手書きのラフや画像でも、プリントできるデータへの調整をサポートします。'],['後日、同じデザインで追加注文できますか？','可能です。シルクスクリーンの版は1年間保管しているため、期間内なら製版代は不要です。DTFは素材代とプリント代のみで追加制作できます。'],['持ち込みの素材・ウェアにプリントできますか？','品質保証の観点から、基本は弊社指定のカタログ商品へのプリントをお願いしています。持ち込み希望は事前にご相談ください。'],['注文してから納品までどのくらいかかりますか？','デザイン確定後、通常2〜3週間でのお渡しです。枚数や時期で変わるため、お急ぎの場合はご相談ください。']]; return <><PageHeading label="よくある質問" en="Q&A" intro="気になることは、LINEでそのまま聞いていただけます。"/><div className="faq">{qs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></> }
function About() { return <><PageHeading label="asoBe（アソビ）とは？" en="ABOUT ASOBE" intro="安心して働ける環境と、一人ひとりが自分らしく成長できる機会を提供しています。"/><section className="about"><div className="about-logo">asoBe<span>SUPPORT</span></div><div><h2>余裕を持って、人生を楽しく。</h2><p>asoBeは、働く意欲はあるけれど、さまざまな事情により一般企業での就労が難しい方々を対象に、安心して働ける環境を提供する就労継続支援B型事業所です。</p><p>「利用者も支援者も、余裕を持って人生を楽しく過ごしてほしい」。事業所名の「asoBe（アソビ）」は、そんな想いから名づけられました。</p><p>ブドウ農園でのワイン作りやアパレルグッズ制作など、クリエイティブなモノづくりを通じて、利用者の一人ひとりが自信につながる体験や知識を得られるサポートをしています。</p><dl><dt>運営元</dt><dd>株式会社 MODESTLY</dd><dt>所在地</dt><dd>長野県松本市蟻ケ崎東1-4-26 ムラタビル2F</dd><dt>連絡先</dt><dd>TEL 0263-31-0913</dd></dl></div></section></> }
function App() { const [page,setPage]=useState(()=>location.hash.replace('#','')||'home'); useEffect(()=>{const change=()=>setPage(location.hash.replace('#','')||'home');addEventListener('hashchange',change);return()=>removeEventListener('hashchange',change)},[]); const content={price:<Price/>,order:<Order/>,print:<Print/>,data:<Data/>,faq:<Faq/>,about:<About/>}[page]; return <div className="site-shell"><header><a className="brand" href="#home" aria-label="asoBe STORE ホーム">asoBe <span>STORE</span></a></header><main>{page==='home'?<><section className="hero"><p className="eyebrow">SILK SCREEN & DTF PRINTING</p><h1>つくりたい、を<br/><em>カタチ</em>に。</h1><p>オリジナルウェア・グッズのプリントを、<br/>LINEから気軽にご相談ください。</p></section><nav className="menu-grid" aria-label="案内メニュー">{pages.map(p=><a href={`#${p.id}`} key={p.id}><span className={`icon icon-${p.id}`}>{p.icon}</span><strong>{p.title}</strong><small>{p.en}</small></a>)}</nav><p className="home-note">写真・手書きラフだけでも、お見積もりできます。</p></>:<><button className="back" onClick={()=>location.hash='home'}>← メニューに戻る</button><article className="content">{content}</article></>}</main><footer><a href="https://asobe202007.com/concept/" target="_blank" rel="noreferrer">asoBeのWebサイトはこちら <span aria-hidden="true">↗</span></a></footer></div> }
export default App
